services:
  server:
    build: ./server
    container_name: ssh-server-container
    image: ssh-server
    networks:
      - ssh-net

  client:
    build: ./client
    container_name: ssh-client-container
    image: ssh-client
    stdin_open: true
    tty: true
    networks:  
      - ssh-net
      
networks:
  ssh-net:
    driver: bridge